filter_phrases = [
    "positive outcome of interim analysis",
    "millions to generate creator content",
    "signs equipment testing agreement with",
    "approves manufacturing line for shipment",
    "transaction values company at",
    "to sell travel vaccines",
    "reports fda advisory committees",
    "exclusive licensing agreement",
    "to enter into clean energy industry",
    "fda advisers back",
    "a compound approved by",
    "equity investment in",
    "the amending agreement was unanimously approved by the board",
    "fda authorizes",
    "create antibody drug conjugates",
    "authorization from fda",
    "holds exclusive global rights to",
    "successful preclinical proof-of-mechanism studies",
    "asset purchase agreement with",
    "formally agreed to purchase through a signed agreement",
    "fda approves",
    "rolling out a new facility",
]
